### ISSUE TITLE
Problems with storing output in a file

### ISSUE THREAD

**Issue by 0cirius0** [s0md3v/Arjun#101]
Sometimes in case the distro crashes while the script is running and fetching input from a long list of URLS, or when a URL makes and exception and the script crashes in between; then the process that is already done is also not outputted.

I have made this pull request #100, which will keep updating the output file with every URL's data as soon as it is finished processing.

**Comment by hellrider9** [comment]
Donno what had happened earlier as I remember forking from latest.
Here I made the changes #103

**Comment by fardeen-ahmed** [comment]
The crash happens in Linux because of heavy threading. Change the threading to minimum. This might help you more.
Crashing happens either of junk scans getting filled during threading, or because of low-configured systems and hardware.

If not, do explain the problem, of what you encouter when the crash again happens.

**Comment by s0md3v** [comment]
This issue has been fixed in 2.1.6 🎉 

Thanks for being patient, it wasn't easy due to introduction of multiple export types in arjun.
