### ISSUE TITLE
Transmission Optimization via Variable Name Equivalence Discovery

### ISSUE THREAD

**Issue by decal** [s0md3v/Arjun#15]
For known query parameters, test if the application behavior changes when different capitalization rules are applied to the variable name, i.e. if the parameter is **_redirect_uri_**, then check how the application responds to: REDIRECT_URI, Redirect_uri.  If the app response doesn't change, then remove in-memory parameter database entries (loaded from `param.txt`) to reduce required protocol data transmissions.

Similarly, provision a separate fingerprinting process to find any stripped characters classes.  In other words, test  **_redirect_uri_** and **_redirecturi_** individually.  If they act identical, all in-memory param DB entries with underscores can be removed.

**Comment by s0md3v** [comment]
I took another another look at it again and looks like it's of no use because both `nonExistingParameter` and `nonexistingparameter` will behave the same way and we have no way to find out if the web application is case sensitive about it.
It's only possible if we have an already known parameter but it's still not worth as the reduced number of parameters will be much less than the total number of parameters i.e. 25,980 which doesn't make much of a difference.
