### ISSUE TITLE
Arjun stuck at "Probing the target for stability"

### ISSUE THREAD

**Issue by s3rdz0x** [s0md3v/Arjun#201]
Hi! 
Recently, I used arjun to scan a list of subdomains and encountered an issue.
So, every time arjun got to a specific URL, it would just freeze at "Probing the target for stability" and it would stay like that. The tool doesn't continue/skip to the next URL.
Did anyone else experience this? It would be great if you could help me out :D

**Comment by iambouali** [comment]
Same issue here.

**Comment by s0md3v** [comment]
Looking into it.

**Comment by hprop1** [comment]
@s0md3v same issue here, has this been resolved yet?
![image](https://github.com/s0md3v/Arjun/assets/157467573/798d2928-4b15-4387-8284-6a2ce6f640ce)
I am running insiderPHDs Generic University Lab and I know there are parameters, at `/api/users` endpoint even InsiderPHD found them with her arjun in this vid https://www.youtube.com/watch?v=fvcKwUS4PTE&list=PLbyncTkpno5HqX1h2MnV6Qt4wvTb8Mpol&index=9, min 45:30

**Comment by NotoriousRebel** [comment]
Same issue here as well, think one possible solution would be to add a --threshold flag or something along the lines where you can do something like ``--threshold 60` and after 60 minutes arjun would automatically start scanning the next url. It's not a perfect solution but is at least a feasible one that shouldn't be too hard to implement.

**Comment by NotoriousRebel** [comment]
@s3rdz0x @iambouali @s0md3v @c137-hacker-rick After debugging the issue and while I can't provide the url I am using it should be easy enough to replicate. The problem is that infinite recursion is occurring in these [lines](https://github.com/s0md3v/Arjun/blob/master/arjun/__main__.py#L138-#L142) in main.py. I have only started using this tool as of yesterday so it is hard for me to give possible solutions as I don't understand the entire codebase and how the compare function normally operates. You can confirm the infinite recursion by adding a simple print statement right before this [line](https://github.com/s0md3v/Arjun/blob/master/arjun/core/anomaly.py#L60) in anomaly.py : `print(f'Currently comparing: {response} {factors} and: {params}')` A possible solution could be changing it from `while factors:` to `for same_header in factors[same_headers])?

**Comment by s0md3v** [comment]
Thank you for your patience. This issue has been fixed in the latest update.

CC: @NotoriousRebel @iambouali @s3rdz0x @c137-hacker-rick
