### ISSUE TITLE
Unable to verify target's SSL certificate.

### ISSUE THREAD

**Issue by robdollard** [s0md3v/Arjun#5]
What to do with such an error? Is it possible to bypass it? The certificate and the truth does not belong to the tested resource, but I still would like to continue the requests.

![image](https://user-images.githubusercontent.com/40629638/46149107-fa8ece00-c282-11e8-9203-47050d282fcb.png)

**Comment by 0blio** [comment]
I have the same problem here.
It's odd because I know `requester.py` try to ignore the SSL certificate but it doesn't seem to work.

**Comment by s0md3v** [comment]
Hi @0blio ,

This bug is caused by poor or outdated implementation of SSL and the `urllib3` doesn't support such implementations and hence errors out.

Unfortunately, this isn't something I control and it can't be fixed. Yes, I tried to ignore SSL verification but it doesn't work for some reason and the maintainers of `requests` library blame it again on the `urllib3`.

Arjun works fine on most of the website and that's the best we can do.

**Comment by 0blio** [comment]
Ok! Thanks for the support.
